site_name: 工试学长组资料汇总
site_author: 工试学长组
site_url: https://zju-enginpilot.github.io/Kickstart/
site_description: 工试学长组资料汇总网站

repo_name: Kickstart
repo_url: https://github.com/ZJU-EnginPilot/Kickstart
edit_uri: tree/main/docs/

copyright: Copyright &copy; 2024 - 2025 浙江大学工科试验班学长组

theme:
  name: material
  language: zh
  favicon: images/LOGO.png
  icon:
    logo: material/book-education-outline
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    view: material/file-eye-outline
  custom_dir: overrides
  features:
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.tabs
    - navigation.top
    - navigation.indexes  # 点击小节名字自动显示 index 界面
    - navigation.footer # 底部导航栏
    - navigation.instant # 站内瞬移
    - navigation.instant.progress
    - toc.integrate   # 单栏 toc
    - toc.follow  # 右侧目录跟随滚动
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit # git edit page
    - content.tooltips
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"  # 浅色模式
      scheme: default
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"   # 深色模式
      scheme: slate
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式

  font:
    text: Roboto
    code: Roboto Mono

extra:
  analytics:
    provider: google
    property: G-9WENM1FP2P
    feedback:
      title: 这个页面对你有帮助吗？
      ratings:
        - icon: material/thumb-up-outline
          name: 帮助很大！
          data: 1
          note: >-
            感谢你的反馈！😘
        - icon: material/thumb-down-outline
          name: 有待改进！
          data: 0
          note: >- 
            感谢你的反馈! 为这个网站项目做<a href="https://zju-enginpilot.github.io/Kickstart/contribution/" target="_blank" rel="noopener">贡献</a>，
            一起让它变得更好！🚀

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - md_in_html
  - attr_list
  - toc:
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - git-committers:
      enabled: !ENV [CI, false]
      repository: ZJU-EnginPilot/Kickstart
      branch: main
  - minify:
      minify_html: true # 加快网页加载速度
  - statistics:
      page_check_metadata: comment

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js   # MathJax 3

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

nav:
  - 主页: 
    - "index.md"
    - 有问题问谁？: "contact.md"
    - 如何贡献: "contribution.md"
    - 友情链接: "links.md"
  - 入学 !:
    - "Enroll/index.md"
    - 入学前准备: "Enroll/Preparation.md"
    - 报到: "Enroll/Orientation.md"
  - 军训:
    - "MT/index.md"
    - 军训日程: "MT/Schedule.md"
    - 军训活动: "MT/Activities.md"
    - 注意事项: "MT/Note.md"
    - 考核: "MT/Assessment.md"
  - 学习:
    - "Study/index.md"
    - 学业基本制度: "Study/Concepts.md"
    - 体育: "Study/PE.md"
    - 选课: "Study/CourseSelection.md"
    - 工试课程经验: 
      - "Study/CourseExperience/index.md"
      - 工程训练: "Study/CourseExperience/工程训练食用指南.md"
      - 机械制图及CAD基础: "Study/CourseExperience/机械制图及CAD基础.md"
    - 工试专业简介: "Study/Majors.md"
    - 专业选择: "Study/MajorSelection.md"
  - 生活: 
    - "Life/index.md"
    - 安全: "Life/Safety.md"
    - 衣: "Life/Clothes.md"
    - 食: "Life/Food.md"
    - 住: "Life/Accommodation.md"
    - 行: "Life/Transportation.md"
    # - 游: "Life/Entertainment.md"
    - 重要地点: "Life/Places.md"
    - 活动: "Life/Activities.md"
    - 学生组织和社团: "Life/Clubs.md"
  - 线上平台:
    - "Online/index.md"
    - 校园网: "Online/ZJUNet.md"
    - 浙大钉: "Online/ZJUDing.md"
    - 软件（APP）: "Online/APP.md"
    - 微信公众号: "Online/WeChat.md"
    - 学习平台: "Online/Learning.md"
    - 论坛: "Online/Forum.md"
    - 其他: "Online/Others.md"
  - 技能: 
    - "Skills/index.md"
    - 电脑基本操作: "Skills/PCop.md"
  - 拓展阅读: "More/index.md"